# Configuration is now managed by the Config Server
# See bootstrap.yml for config server settings

# Auth Service Configuration

server:
  port: 8083

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8888
  
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:youremail@gmail.com}
    password: ${MAIL_PASSWORD:yourpassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 10
  instance:
    prefer-ip-address: true
    hostname: localhost

app:
  jwtSecret: 9a4f2c8d3b7e1a5f2c8d3b7e1a5f2c8d3b7e1a5f2c8d3b7e1a5f2c8d3b7e1a5f
  jwtExpirationInMs: 86400000
  refreshTokenExpirationMs: 604800000
  url: http://localhost:3000 