# Configuration is now managed by the Config Server
# See bootstrap.yml for config server settings

# API Gateway Configuration

server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://auth-service
          predicates:
            - Path=/api/users/**
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/courses/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

app:
  jwtSecret: 9a4f2c8d3b7e1a5f2c8d3b7e1a5f2c8d3b7e1a5f2c8d3b7e1a5f2c8d3b7e1a5f

# Logging for troubleshooting
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG 