# Configuration is now managed by the Config Server
# See bootstrap.yml for config server settings

# Discovery Service Configuration

server:
  port: 8761

spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

# Logging for troubleshooting
logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG 